[general]
name = "docpage-generator"
version = "0.2.0"
fix_version = "1.3.0"
authors = ["tttmmmyyyy"]
license = "MIT"

[build]
files = ["main.fix"]

[[dependencies]]
name = "subprocess"
version = "1.0.1"
git = { url = "https://github.com/tttmmmyyyy/fixlang-subprocess.git" }

[[dependencies]]
name = "minilib-json"
version = "0.5.1"
git = { url = "https://github.com/pt9999/fixlang-minilib-json.git" }

[[dependencies]]
name = "ez-scripting"
version = "0.1.0"
git = { url = "https://github.com/tttmmmyyyy/ez_scripting.git" }
