site_name: Fix DocPage
theme: 
  name: material
  custom_dir: custom_theme
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search:
      lang: en
      separator: '[\s\-\._]+'
      # 検索の柔軟性を高める設定
      pipeline:
        - trimmer

extra_javascript:
  - javascripts/search-boost.js
